ci: linter 확인하는 Github Action 추가
hyunW3/react_practice pull request #18
Opened 2021-10-09 05:28 UTC by sjuuun

## 무엇이 변경되었나요?

- linter를 확인하는 Github Action을 추가했어요.
  - master에 새로운 커밋이 있을 때, pull_request에서 돌아갑니다.
- issue_template, pull_request_template을 추가했어요.

## 추가로 알아야 할 사항
- commit 할 때 git hook로 linter를 확인하지만, CI로 한번 더 확인하도록 해봤어요.
- Github Action 환경에서는 DB 정보가 없어서 unresolved_import error가 떠요 → warning으로 변경했어요.
  - DB 정보를 환경변수로 관리한다면, unresolved_import가 뜨지 않을 수 있지만.. 나중에 고칠게요.
- 현재 CI는 대략 1분 정도 걸려요. 무료 플랜은 한달에 2000분이에요. (참고 - [GitHub Action Billing](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions))
- issue, pull_request template은 새로운 이슈나 PR 추가할 때 편하라고 만들어뒀어요! + 꼭 필요한 내용은 적고 넘어가자는 취지에요.
  - 혹시 추가할 내용이 있다면 코멘트 쿠다사이!
- github action cache를 추가했어요 - 참고 [Github Action Cache](https://github.com/actions/cache/blob/main/examples.md#node---npm)

2021-10-09 06:05 UTC, hyunW3 approved these changes
## Comment
- 도입해주셔서 감사합니다!
- DB 정보를 환경변수로 github action에서 관리하는 것 찬성입니다!

## Suggestion
- actions/cache@v2 를 활용하면 설치된 npm 모듈을 캐시할수 있다고 하네요. client부분에 npm install 부분이 40초 가량이 되니, 제가 생각하는 캐시하는 것이 맞다면 ci 시간을 줄일 수 있을 것같아요 ( + client 부분의 npm module 다이어트를 해볼게요...!)
	- referene : https://devblog.croquis.com/ko/2020-11-06-1-using-github-actions/

2021-10-09 11:44 UTC, sjuuun commented
> actions/cache@v2 를 활용하면 설치된 npm 모듈을 캐시할수 있다고 하네요.

41e095d 에서 적용했어요!

2021-10-09 11:49 UTC, sjuuun commented
> > actions/cache@v2 를 활용하면 설치된 npm 모듈을 캐시할수 있다고 하네요.
> 
> [41e095d](https://github.com/hyunW3/BlogReact/commit/41e095d2463edfb70325c2954fd00c80c7773a81) 에서 적용했어요!

흠 근데 cache가 잘 적용되는지는 모르겠네요.. ci 도는 시간이 비슷해요

2021-10-09 12:26 UTC, hyunW3 commented
> > > actions/cache@v2 를 활용하면 설치된 npm 모듈을 캐시할수 있다고 하네요.
> > 
> > 
> > [41e095d](https://github.com/hyunW3/BlogReact/commit/41e095d2463edfb70325c2954fd00c80c7773a81) 에서 적용했어요!
> 
> 흠 근데 cache가 잘 적용되는지는 모르겠네요.. ci 도는 시간이 비슷해요

cache니까 적용하고 난뒤에 한번만 돌린거면 cache hit 가 되지 않아서 그럴수도 있지않을까요!? 이제 cache에 올라간것이죠. 다음번에도 비슷하면 issue에 올려야겠네요.

2021-10-10 11:56 UTC, hyunW3 commented
## Comment
- 와우.. 빠른 피드백 및 도입 감사합니다.
- 읽어보면서 CI에 대해서 조금 더 이해했어요
- 관련 질문은 코드에 달아볼게요.

2021-10-10 12:02 UTC, hyunW3 requested changes
CI환경에서 npm install 질문한 부분 해결되면 Approve 하겠습니다. 고생하셨어요!

2021-10-10 12:02 UTC, hyunW3 commented on .github/workflows/check-lint.yml
> +      run: npm install
cache를 사용하는데, npm install 에서 cache hit일경우 스킵하는 조건문이 따로 없는 것같아요. 의도한 것인가요?
-> if: steps.node-cache.outputs.cache-hit != 'true' 와 같은 것이요
	- reference : https://whitekiwi.medium.com/github-actions-cache-node-modules-99935de9e8fa

2021-10-10 12:02 UTC, hyunW3 commented on .gitignore
> +**/.DS_Store
DS_store는 맥용 파일인 것이죠? 저렇게 수정한 이유가 뭐에요?

2021-10-10 12:02 UTC, hyunW3 commented on server/.eslintrc.json
> +        "import/no-unresolved": ["warn", { "caseSensitive": false }]
import/no-unresolved 문제는 어느 상황에서 발생하나요? 혹시 CI 진행중에 발생하는 문제인가요?

2021-10-10 12:02 UTC, hyunW3 commented on .github/workflows/check-lint.yml
> +        node-version: '16'
CI뿐만아니라 작업하는 node 버젼도 16으로 올리는 게 좋을까요? (다르게 말하면 CI시의 버젼과 작업환경 버젼을 
 일치시키는 게 좋을까요?)

2021-10-10 12:52 UTC, sjuuun commented on .github/workflows/check-lint.yml
> +      run: npm install
오호 그냥 `npm install` 하면 캐싱된 모듈을 사용하지 않을까 생각했는데, 아닌 것 같네요.
cache hit일 경우는 스킵하면 좋은 것 같아요.

근데, `setup-node` 쪽에서 cache 사용하는 옵션이 있어서 [이걸](https://github.com/actions/setup-node#caching-packages-dependencies) 써도 될 것 같아요. 캐싱 기능은 동일한테 내부적으로 설정을 알아서 해줘서 사용하기는 훨 편해보여요.

2021-10-10 12:53 UTC, sjuuun commented on .gitignore
> +**/.DS_Store
맥용 캐싱 파일로 알고 있는데, 모든 디렉토리에서 `.DS_Store`을 git ignore 하도록 변경한거에요.
(사실 굳이 고칠 필요 없는데.. ci 다시 돌려보려고 수정해봤음 ㅎㅎ)

2021-10-10 12:54 UTC, sjuuun commented on server/.eslintrc.json
> +        "import/no-unresolved": ["warn", { "caseSensitive": false }]
> Github Action 환경에서는 DB 정보가 없어서 unresolved_import error가 떠요 → warning으로 변경했어요.
> DB 정보를 환경변수로 관리한다면, unresolved_import가 뜨지 않을 수 있지만.. 나중에 고칠게요.

얍얍 CI에서 mongo db config를 import 할 수 없다고 뜨더라구요.

2021-10-10 12:55 UTC, sjuuun commented on .github/workflows/check-lint.yml
> +        node-version: '16'
통일하는게 좋죠! node 15부터 npm workspace가 도입된 것 같아서 16으로 통일하면 좋을 것 같아요.
참고 - https://blog.logrocket.com/node-js-15-whats-new-and-how-the-developer-experience-has-improved/

2021-10-10 13:09 UTC, hyunW3 commented on .gitignore
> +**/.DS_Store
아하 저게 그 뜻이구나 알겠습니다:)

2021-10-10 13:26 UTC, hyunW3 commented on .github/workflows/check-lint.yml
> +        node-version: '16'
네 좋아요 16.11.0으로 node version 통일할게요.

2021-10-10 13:28 UTC, hyunW3 commented on .github/workflows/check-lint.yml
> +      run: npm install
네 좋아요:) b8e0dd4 확인했어요

2021-10-10 13:29 UTC, hyunW3 commented on server/.eslintrc.json
> +        "import/no-unresolved": ["warn", { "caseSensitive": false }]
감사합니다. 다른 import 문제에서도 발생되었을 떄 못 찾을수도 있으니까 issue로 올리는게 좋을거같아요

2021-10-10 13:31 UTC, sjuuun commented on server/.eslintrc.json
> +        "import/no-unresolved": ["warn", { "caseSensitive": false }]
#20

2021-10-10 13:33 UTC, hyunW3 approved these changes
## Comment
고생하셨어요.

2021-10-10 13:33 UTC, merged