feat : 👍 버튼 구현 및 DB 업데이트 추가
hyunW3/react_practice pull request #32
Opened 2021-11-11 13:42 UTC by hyunW3

## 무엇이 변경되었나요?

- 컨텐츠 내용과 관련한 👍 버튼 및 업데이트된 정보를 DB에 update하는 기능을 구현했습니다. 

## 관련된 ISSUE 혹은 PR은 무엇인가요?

#26 👍 정보 저장하기

## 추가로 알아야 할 것을 알려주세요! (선택사항)

하다보니까 클라이언트 뿐만 아니라 서버쪽도 해버렸네요 ㅎㅎ..

2021-11-11 13:52 UTC, hyunW3 commented
백앤드 커밋할때 pre-commit 이 적용이 안되네요

2021-11-11 14:04 UTC, hyunW3 commented
b98b71b : pre-commit 적용안되는 문제 해결했습니다.

2021-11-13 11:00 UTC, sjuuun requested changes
좋네좋아 아주 좋아요 ㅎㅎ
PR 제목 바꿔주세요!

2021-11-13 11:00 UTC, sjuuun commented on client/src/components/PageContentsList.js
> +  const latestContents = useRef();
useRef 가 어떤건지 간략하게 설명 가능할까요? 잘 이해 안되서요 ㅎㅎ

2021-11-13 11:00 UTC, sjuuun commented on client/src/components/PageContentsList.js
> +        },
참고차 남기자면, 업데이트를 위해 `PATCH` 나 `PUT` 이라는 method 도 존재해요. (실제로 잘 쓰이는지는 모르겠지만..)

2021-11-13 11:00 UTC, sjuuun commented on server/package.json
> +    "./**/*.{js, jsx}": [
src 말고 다른 js 파일이 있나요?

2021-11-13 11:00 UTC, sjuuun commented on server/routes/content.js
> +  }
그냥 `req.body.foreach` 로 하나하나 돌면서 업데이트하면 안되나요?
updateIdList 랑 updateThumbList 를 분리해서 다시 for 문을 돌 필요 없이, 그냥 request body 에서 바로 foreach 로 돌면서 업데이트 할 수 있을 것 같아서요

2021-11-13 11:00 UTC, sjuuun commented on server/routes/content.js
> +  }
이건 그냥 던져보는건데, 이렇게 하나하나 한다면 어떤 문제가 있을가요?
지금은 상관 없지만 업데이트 할 것들이 많아진다면, 하나하나 업데이트 하는 방식이 오래걸릴 것 같아서요 ㅎㅎ

https://kb.objectrocket.com/mongo-db/how-to-use-mongoose-to-update-in-bulk-930
`updateMany` 가 이걸 도와줄까요?

지금 저 방식을 수정할 필요는 없어보여요! 그냥 궁금해서...ㅎㅎ

2021-11-13 11:00 UTC, sjuuun commented on server/routes/content.js
> +  await Promise.all(contents.contentSchema);
이건.. DB 업데이트가 끝날 때까지 기다리는건가요?

2021-11-14 07:57 UTC, hyunW3 commented on client/src/components/PageContentsList.js
> +  const latestContents = useRef();
간단하게 말하면 contents의 최신 값을 가져오기 위해서 활용합니다. (아래 부분은 최신 값을 따로 저장하는 이유에요)
UseEffect()함수에서 return 하는 함수인 Update함수 호출시, useState() 라는 state를 저장하는 함수를 이용하면 컴포넌트를 처음 랜더링시 초기화된 값(const [contents, setContents] =  useState([])이라하면 -> [] 즉, 빈배열이 해당됩니다.)이 contents에 할당되어 있더라고요. (리랜더링하고 클린업 함수 실행 - 리액트 생애주기랑 관련있습니다.)

2021-11-14 07:58 UTC, hyunW3 commented on client/src/components/PageContentsList.js
> +    latestContents.current = newArr;
> 간단하게 말하면 contents의 최신 값을 가져오기 위해서 활용합니다. (아래 부분은 최신 값을 따로 저장하는 이유에요) UseEffect()함수에서 return 하는 함수인 Update함수 호출시, useState() 라는 state를 저장하는 함수를 이용하면 컴포넌트를 처음 랜더링시 초기화된 값(const [contents, setContents] = useState([])이라하면 -> [] 즉, 빈배열이 해당됩니다.)이 contents에 할당되어 있더라고요. (리랜더링하고 클린업 함수 실행 - 리액트 생애주기랑 관련있습니다.)

최신 값을 업데이트 하는 부분이에요.

2021-11-14 07:58 UTC, hyunW3 commented on client/src/components/PageContentsList.js
> +        },
오호.. 관련해서 찾아봐야겠네요 감사합니다:)

2021-11-14 07:59 UTC, hyunW3 commented on server/routes/content.js
> +  await Promise.all(contents.contentSchema);
네 맞아요. for문으로 간단하게 해결하고 싶었는데, for문내에 await를 사용하지 못하더라고요.

2021-11-14 08:03 UTC, hyunW3 commented on server/routes/content.js
> +  }
> 이건 그냥 던져보는건데, 이렇게 하나하나 한다면 어떤 문제가 있을가요? 지금은 상관 없지만 업데이트 할 것들이 많아진다면, 하나하나 업데이트 하는 방식이 오래걸릴 것 같아서요 ㅎㅎ
> [kb.objectrocket.com/mongo-db/how-to-use-mongoose-to-update-in-bulk-930](https://kb.objectrocket.com/mongo-db/how-to-use-mongoose-to-update-in-bulk-930) `updateMany` 가 이걸 도와줄까요?
> 지금 저 방식을 수정할 필요는 없어보여요! 그냥 궁금해서...ㅎㅎ

저도 처음에는 updateMany로 해결하고 싶었는데, 저희가 의도한 DB request인지는 확인해야할 것같아요. 
- 제가 document를 읽었을 때는, updateOne(A,B) 은 A에 해당되는 DB가 여러개 있어도 하나만 B로 변경해주는 것이고, updateMany(A,B)는 A에 해당되는 DB가 여러개라면 모두 B로 변경해주는 것으로 이해했거든요. 저희가 의도하는 기능은 A[0]에 해당되는 DB를 B[0]로 변경하고, A[1]에 해당되는 것을 B[1]로 변경하고 이런 기능이거든요. (Front에서 그렇게 데이터를 보내주기도 하거든요.)

2021-11-14 13:00 UTC, hyunW3 commented on client/src/components/PageContentsList.js
> +        },
18e6085 해당 부분으로 변경하였습니다. (POST -> PATCH)

2021-11-14 13:01 UTC, hyunW3 commented on server/routes/content.js
> +  }
> 그냥 `req.body.foreach` 로 하나하나 돌면서 업데이트하면 안되나요? updateIdList 랑 updateThumbList 를 분리해서 다시 for 문을 돌 필요 없이, 그냥 request body 에서 바로 foreach 로 돌면서 업데이트 할 수 있을 것 같아서요

351acfd 해당 부분 적용했어요.

2021-11-14 14:21 UTC, sjuuun approved these changes

2021-11-14 14:22 UTC, merged